const githubResult = """
{
  "total_count": 33,
  "incomplete_results": false,
  "items": [
    {
      "login": "jaelson",
      "id": 11576330,
      "node_id": "MDQ6VXNlcjExNTc2MzMw",
      "avatar_url": "https://avatars.githubusercontent.com/u/11576330?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson",
      "html_url": "https://github.com/jaelson",
      "followers_url": "https://api.github.com/users/jaelson/followers",
      "following_url": "https://api.github.com/users/jaelson/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson/orgs",
      "repos_url": "https://api.github.com/users/jaelson/repos",
      "events_url": "https://api.github.com/users/jaelson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsondev",
      "id": 23247832,
      "node_id": "MDQ6VXNlcjIzMjQ3ODMy",
      "avatar_url": "https://avatars.githubusercontent.com/u/23247832?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsondev",
      "html_url": "https://github.com/jaelsondev",
      "followers_url": "https://api.github.com/users/jaelsondev/followers",
      "following_url": "https://api.github.com/users/jaelsondev/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsondev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsondev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsondev/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsondev/orgs",
      "repos_url": "https://api.github.com/users/jaelsondev/repos",
      "events_url": "https://api.github.com/users/jaelsondev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsondev/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonrc",
      "id": 16440205,
      "node_id": "MDQ6VXNlcjE2NDQwMjA1",
      "avatar_url": "https://avatars.githubusercontent.com/u/16440205?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonrc",
      "html_url": "https://github.com/jaelsonrc",
      "followers_url": "https://api.github.com/users/jaelsonrc/followers",
      "following_url": "https://api.github.com/users/jaelsonrc/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonrc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonrc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonrc/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonrc/orgs",
      "repos_url": "https://api.github.com/users/jaelsonrc/repos",
      "events_url": "https://api.github.com/users/jaelsonrc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonrc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonwagner",
      "id": 3064763,
      "node_id": "MDQ6VXNlcjMwNjQ3NjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3064763?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonwagner",
      "html_url": "https://github.com/jaelsonwagner",
      "followers_url": "https://api.github.com/users/jaelsonwagner/followers",
      "following_url": "https://api.github.com/users/jaelsonwagner/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonwagner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonwagner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonwagner/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonwagner/orgs",
      "repos_url": "https://api.github.com/users/jaelsonwagner/repos",
      "events_url": "https://api.github.com/users/jaelsonwagner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonwagner/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jcarva",
      "id": 13679327,
      "node_id": "MDQ6VXNlcjEzNjc5MzI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/13679327?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jcarva",
      "html_url": "https://github.com/jcarva",
      "followers_url": "https://api.github.com/users/jcarva/followers",
      "following_url": "https://api.github.com/users/jcarva/following{/other_user}",
      "gists_url": "https://api.github.com/users/jcarva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jcarva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jcarva/subscriptions",
      "organizations_url": "https://api.github.com/users/jcarva/orgs",
      "repos_url": "https://api.github.com/users/jcarva/repos",
      "events_url": "https://api.github.com/users/jcarva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jcarva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonapolinario",
      "id": 6399078,
      "node_id": "MDQ6VXNlcjYzOTkwNzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399078?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonapolinario",
      "html_url": "https://github.com/jaelsonapolinario",
      "followers_url": "https://api.github.com/users/jaelsonapolinario/followers",
      "following_url": "https://api.github.com/users/jaelsonapolinario/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonapolinario/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonapolinario/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonapolinario/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonapolinario/orgs",
      "repos_url": "https://api.github.com/users/jaelsonapolinario/repos",
      "events_url": "https://api.github.com/users/jaelsonapolinario/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonapolinario/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson001",
      "id": 48810013,
      "node_id": "MDQ6VXNlcjQ4ODEwMDEz",
      "avatar_url": "https://avatars.githubusercontent.com/u/48810013?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson001",
      "html_url": "https://github.com/jaelson001",
      "followers_url": "https://api.github.com/users/jaelson001/followers",
      "following_url": "https://api.github.com/users/jaelson001/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson001/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson001/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson001/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson001/orgs",
      "repos_url": "https://api.github.com/users/jaelson001/repos",
      "events_url": "https://api.github.com/users/jaelson001/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson001/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "elquintela",
      "id": 42502325,
      "node_id": "MDQ6VXNlcjQyNTAyMzI1",
      "avatar_url": "https://avatars.githubusercontent.com/u/42502325?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/elquintela",
      "html_url": "https://github.com/elquintela",
      "followers_url": "https://api.github.com/users/elquintela/followers",
      "following_url": "https://api.github.com/users/elquintela/following{/other_user}",
      "gists_url": "https://api.github.com/users/elquintela/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/elquintela/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/elquintela/subscriptions",
      "organizations_url": "https://api.github.com/users/elquintela/orgs",
      "repos_url": "https://api.github.com/users/elquintela/repos",
      "events_url": "https://api.github.com/users/elquintela/events{/privacy}",
      "received_events_url": "https://api.github.com/users/elquintela/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson-ciandt",
      "id": 26466067,
      "node_id": "MDQ6VXNlcjI2NDY2MDY3",
      "avatar_url": "https://avatars.githubusercontent.com/u/26466067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson-ciandt",
      "html_url": "https://github.com/jaelson-ciandt",
      "followers_url": "https://api.github.com/users/jaelson-ciandt/followers",
      "following_url": "https://api.github.com/users/jaelson-ciandt/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson-ciandt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson-ciandt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson-ciandt/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson-ciandt/orgs",
      "repos_url": "https://api.github.com/users/jaelson-ciandt/repos",
      "events_url": "https://api.github.com/users/jaelson-ciandt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson-ciandt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "hederguerreiro",
      "id": 916619,
      "node_id": "MDQ6VXNlcjkxNjYxOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/916619?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hederguerreiro",
      "html_url": "https://github.com/hederguerreiro",
      "followers_url": "https://api.github.com/users/hederguerreiro/followers",
      "following_url": "https://api.github.com/users/hederguerreiro/following{/other_user}",
      "gists_url": "https://api.github.com/users/hederguerreiro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hederguerreiro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hederguerreiro/subscriptions",
      "organizations_url": "https://api.github.com/users/hederguerreiro/orgs",
      "repos_url": "https://api.github.com/users/hederguerreiro/repos",
      "events_url": "https://api.github.com/users/hederguerreiro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hederguerreiro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonhenrique",
      "id": 54916795,
      "node_id": "MDQ6VXNlcjU0OTE2Nzk1",
      "avatar_url": "https://avatars.githubusercontent.com/u/54916795?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonhenrique",
      "html_url": "https://github.com/jaelsonhenrique",
      "followers_url": "https://api.github.com/users/jaelsonhenrique/followers",
      "following_url": "https://api.github.com/users/jaelsonhenrique/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonhenrique/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonhenrique/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonhenrique/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonhenrique/orgs",
      "repos_url": "https://api.github.com/users/jaelsonhenrique/repos",
      "events_url": "https://api.github.com/users/jaelsonhenrique/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonhenrique/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson91",
      "id": 61023298,
      "node_id": "MDQ6VXNlcjYxMDIzMjk4",
      "avatar_url": "https://avatars.githubusercontent.com/u/61023298?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson91",
      "html_url": "https://github.com/jaelson91",
      "followers_url": "https://api.github.com/users/jaelson91/followers",
      "following_url": "https://api.github.com/users/jaelson91/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson91/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson91/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson91/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson91/orgs",
      "repos_url": "https://api.github.com/users/jaelson91/repos",
      "events_url": "https://api.github.com/users/jaelson91/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson91/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonsantos",
      "id": 7416941,
      "node_id": "MDQ6VXNlcjc0MTY5NDE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7416941?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonsantos",
      "html_url": "https://github.com/jaelsonsantos",
      "followers_url": "https://api.github.com/users/jaelsonsantos/followers",
      "following_url": "https://api.github.com/users/jaelsonsantos/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonsantos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonsantos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonsantos/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonsantos/orgs",
      "repos_url": "https://api.github.com/users/jaelsonsantos/repos",
      "events_url": "https://api.github.com/users/jaelsonsantos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonsantos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonsantos1",
      "id": 80257886,
      "node_id": "MDQ6VXNlcjgwMjU3ODg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/80257886?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonsantos1",
      "html_url": "https://github.com/jaelsonsantos1",
      "followers_url": "https://api.github.com/users/jaelsonsantos1/followers",
      "following_url": "https://api.github.com/users/jaelsonsantos1/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonsantos1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonsantos1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonsantos1/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonsantos1/orgs",
      "repos_url": "https://api.github.com/users/jaelsonsantos1/repos",
      "events_url": "https://api.github.com/users/jaelsonsantos1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonsantos1/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonsalesflash",
      "id": 60299219,
      "node_id": "MDQ6VXNlcjYwMjk5MjE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/60299219?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonsalesflash",
      "html_url": "https://github.com/jaelsonsalesflash",
      "followers_url": "https://api.github.com/users/jaelsonsalesflash/followers",
      "following_url": "https://api.github.com/users/jaelsonsalesflash/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonsalesflash/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonsalesflash/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonsalesflash/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonsalesflash/orgs",
      "repos_url": "https://api.github.com/users/jaelsonsalesflash/repos",
      "events_url": "https://api.github.com/users/jaelsonsalesflash/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonsalesflash/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson500",
      "id": 52861845,
      "node_id": "MDQ6VXNlcjUyODYxODQ1",
      "avatar_url": "https://avatars.githubusercontent.com/u/52861845?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson500",
      "html_url": "https://github.com/jaelson500",
      "followers_url": "https://api.github.com/users/jaelson500/followers",
      "following_url": "https://api.github.com/users/jaelson500/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson500/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson500/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson500/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson500/orgs",
      "repos_url": "https://api.github.com/users/jaelson500/repos",
      "events_url": "https://api.github.com/users/jaelson500/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson500/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonquintela",
      "id": 42502370,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjQyNTAyMzcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/42502370?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonquintela",
      "html_url": "https://github.com/jaelsonquintela",
      "followers_url": "https://api.github.com/users/jaelsonquintela/followers",
      "following_url": "https://api.github.com/users/jaelsonquintela/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonquintela/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonquintela/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonquintela/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonquintela/orgs",
      "repos_url": "https://api.github.com/users/jaelsonquintela/repos",
      "events_url": "https://api.github.com/users/jaelsonquintela/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonquintela/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson7",
      "id": 68622788,
      "node_id": "MDQ6VXNlcjY4NjIyNzg4",
      "avatar_url": "https://avatars.githubusercontent.com/u/68622788?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson7",
      "html_url": "https://github.com/jaelson7",
      "followers_url": "https://api.github.com/users/jaelson7/followers",
      "following_url": "https://api.github.com/users/jaelson7/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson7/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson7/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson7/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson7/orgs",
      "repos_url": "https://api.github.com/users/jaelson7/repos",
      "events_url": "https://api.github.com/users/jaelson7/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson7/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jaelsonweb",
      "id": 30220591,
      "node_id": "MDQ6VXNlcjMwMjIwNTkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/30220591?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jaelsonweb",
      "html_url": "https://github.com/Jaelsonweb",
      "followers_url": "https://api.github.com/users/Jaelsonweb/followers",
      "following_url": "https://api.github.com/users/Jaelsonweb/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jaelsonweb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jaelsonweb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jaelsonweb/subscriptions",
      "organizations_url": "https://api.github.com/users/Jaelsonweb/orgs",
      "repos_url": "https://api.github.com/users/Jaelsonweb/repos",
      "events_url": "https://api.github.com/users/Jaelsonweb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jaelsonweb/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JaelsonC",
      "id": 45217482,
      "node_id": "MDQ6VXNlcjQ1MjE3NDgy",
      "avatar_url": "https://avatars.githubusercontent.com/u/45217482?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JaelsonC",
      "html_url": "https://github.com/JaelsonC",
      "followers_url": "https://api.github.com/users/JaelsonC/followers",
      "following_url": "https://api.github.com/users/JaelsonC/following{/other_user}",
      "gists_url": "https://api.github.com/users/JaelsonC/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JaelsonC/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JaelsonC/subscriptions",
      "organizations_url": "https://api.github.com/users/JaelsonC/orgs",
      "repos_url": "https://api.github.com/users/JaelsonC/repos",
      "events_url": "https://api.github.com/users/JaelsonC/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JaelsonC/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Jaelsonx",
      "id": 51022124,
      "node_id": "MDQ6VXNlcjUxMDIyMTI0",
      "avatar_url": "https://avatars.githubusercontent.com/u/51022124?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Jaelsonx",
      "html_url": "https://github.com/Jaelsonx",
      "followers_url": "https://api.github.com/users/Jaelsonx/followers",
      "following_url": "https://api.github.com/users/Jaelsonx/following{/other_user}",
      "gists_url": "https://api.github.com/users/Jaelsonx/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Jaelsonx/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Jaelsonx/subscriptions",
      "organizations_url": "https://api.github.com/users/Jaelsonx/orgs",
      "repos_url": "https://api.github.com/users/Jaelsonx/repos",
      "events_url": "https://api.github.com/users/Jaelsonx/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Jaelsonx/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson784",
      "id": 42808538,
      "node_id": "MDQ6VXNlcjQyODA4NTM4",
      "avatar_url": "https://avatars.githubusercontent.com/u/42808538?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson784",
      "html_url": "https://github.com/jaelson784",
      "followers_url": "https://api.github.com/users/jaelson784/followers",
      "following_url": "https://api.github.com/users/jaelson784/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson784/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson784/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson784/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson784/orgs",
      "repos_url": "https://api.github.com/users/jaelson784/repos",
      "events_url": "https://api.github.com/users/jaelson784/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson784/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonap",
      "id": 63679972,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjYzNjc5OTcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/63679972?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonap",
      "html_url": "https://github.com/jaelsonap",
      "followers_url": "https://api.github.com/users/jaelsonap/followers",
      "following_url": "https://api.github.com/users/jaelsonap/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonap/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonap/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonap/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonap/orgs",
      "repos_url": "https://api.github.com/users/jaelsonap/repos",
      "events_url": "https://api.github.com/users/jaelsonap/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonap/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JaelsonLima",
      "id": 13764527,
      "node_id": "MDQ6VXNlcjEzNzY0NTI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/13764527?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JaelsonLima",
      "html_url": "https://github.com/JaelsonLima",
      "followers_url": "https://api.github.com/users/JaelsonLima/followers",
      "following_url": "https://api.github.com/users/JaelsonLima/following{/other_user}",
      "gists_url": "https://api.github.com/users/JaelsonLima/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JaelsonLima/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JaelsonLima/subscriptions",
      "organizations_url": "https://api.github.com/users/JaelsonLima/orgs",
      "repos_url": "https://api.github.com/users/JaelsonLima/repos",
      "events_url": "https://api.github.com/users/JaelsonLima/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JaelsonLima/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelsonduckjay",
      "id": 46709341,
      "node_id": "MDQ6VXNlcjQ2NzA5MzQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/46709341?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelsonduckjay",
      "html_url": "https://github.com/jaelsonduckjay",
      "followers_url": "https://api.github.com/users/jaelsonduckjay/followers",
      "following_url": "https://api.github.com/users/jaelsonduckjay/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelsonduckjay/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelsonduckjay/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelsonduckjay/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelsonduckjay/orgs",
      "repos_url": "https://api.github.com/users/jaelsonduckjay/repos",
      "events_url": "https://api.github.com/users/jaelsonduckjay/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelsonduckjay/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JaelsonCavalcante",
      "id": 9487860,
      "node_id": "MDQ6VXNlcjk0ODc4NjA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9487860?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JaelsonCavalcante",
      "html_url": "https://github.com/JaelsonCavalcante",
      "followers_url": "https://api.github.com/users/JaelsonCavalcante/followers",
      "following_url": "https://api.github.com/users/JaelsonCavalcante/following{/other_user}",
      "gists_url": "https://api.github.com/users/JaelsonCavalcante/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JaelsonCavalcante/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JaelsonCavalcante/subscriptions",
      "organizations_url": "https://api.github.com/users/JaelsonCavalcante/orgs",
      "repos_url": "https://api.github.com/users/JaelsonCavalcante/repos",
      "events_url": "https://api.github.com/users/JaelsonCavalcante/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JaelsonCavalcante/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JaelsonTavares",
      "id": 15640823,
      "node_id": "MDQ6VXNlcjE1NjQwODIz",
      "avatar_url": "https://avatars.githubusercontent.com/u/15640823?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JaelsonTavares",
      "html_url": "https://github.com/JaelsonTavares",
      "followers_url": "https://api.github.com/users/JaelsonTavares/followers",
      "following_url": "https://api.github.com/users/JaelsonTavares/following{/other_user}",
      "gists_url": "https://api.github.com/users/JaelsonTavares/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JaelsonTavares/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JaelsonTavares/subscriptions",
      "organizations_url": "https://api.github.com/users/JaelsonTavares/orgs",
      "repos_url": "https://api.github.com/users/JaelsonTavares/repos",
      "events_url": "https://api.github.com/users/JaelsonTavares/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JaelsonTavares/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson1252",
      "id": 17243852,
      "node_id": "MDQ6VXNlcjE3MjQzODUy",
      "avatar_url": "https://avatars.githubusercontent.com/u/17243852?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson1252",
      "html_url": "https://github.com/jaelson1252",
      "followers_url": "https://api.github.com/users/jaelson1252/followers",
      "following_url": "https://api.github.com/users/jaelson1252/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson1252/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson1252/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson1252/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson1252/orgs",
      "repos_url": "https://api.github.com/users/jaelson1252/repos",
      "events_url": "https://api.github.com/users/jaelson1252/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson1252/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "JaelsonFilho",
      "id": 38797926,
      "node_id": "MDQ6VXNlcjM4Nzk3OTI2",
      "avatar_url": "https://avatars.githubusercontent.com/u/38797926?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JaelsonFilho",
      "html_url": "https://github.com/JaelsonFilho",
      "followers_url": "https://api.github.com/users/JaelsonFilho/followers",
      "following_url": "https://api.github.com/users/JaelsonFilho/following{/other_user}",
      "gists_url": "https://api.github.com/users/JaelsonFilho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JaelsonFilho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JaelsonFilho/subscriptions",
      "organizations_url": "https://api.github.com/users/JaelsonFilho/orgs",
      "repos_url": "https://api.github.com/users/JaelsonFilho/repos",
      "events_url": "https://api.github.com/users/JaelsonFilho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JaelsonFilho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "jaelson11",
      "id": 61605801,
      "node_id": "MDQ6VXNlcjYxNjA1ODAx",
      "avatar_url": "https://avatars.githubusercontent.com/u/61605801?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaelson11",
      "html_url": "https://github.com/jaelson11",
      "followers_url": "https://api.github.com/users/jaelson11/followers",
      "following_url": "https://api.github.com/users/jaelson11/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaelson11/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaelson11/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaelson11/subscriptions",
      "organizations_url": "https://api.github.com/users/jaelson11/orgs",
      "repos_url": "https://api.github.com/users/jaelson11/repos",
      "events_url": "https://api.github.com/users/jaelson11/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaelson11/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
